famous_people = [
    {"name": "Cristiano Ronaldo", "profession": "Footballer", "followers_millions": 630},
    {"name": "Lionel Messi", "profession": "Footballer", "followers_millions": 520},
    {"name": "Virat Kohli", "profession": "Cricketer", "followers_millions": 270},
    {"name": "Selena Gomez", "profession": "Singer", "followers_millions": 450},
    {"name": "Dwayne Johnson", "profession": "Actor", "followers_millions": 395},
    {"name": "Kylie Jenner", "profession": "Entrepreneur", "followers_millions": 400},
    {"name": "Kim Kardashian", "profession": "Entrepreneur", "followers_millions": 360},
    {"name": "Taylor Swift", "profession": "Singer", "followers_millions": 390},
    {"name": "Neymar Jr", "profession": "Footballer", "followers_millions": 370},
    {"name": "Ariana Grande", "profession": "Singer", "followers_millions": 380},
    {"name": "Billie Eilish", "profession": "Singer", "followers_millions": 140},
    {"name": "Shah Rukh Khan", "profession": "Actor", "followers_millions": 100},
    {"name": "MS Dhoni", "profession": "Cricketer", "followers_millions": 95},
    {"name": "David Beckham", "profession": "Footballer", "followers_millions": 150},
    {"name": "Zendaya", "profession": "Actress", "followers_millions": 180},
    {"name": "Emma Watson", "profession": "Actress", "followers_millions": 110},
    {"name": "Elon Musk", "profession": "Entrepreneur", "followers_millions": 180},
    {"name": "Jeff Bezos", "profession": "Entrepreneur", "followers_millions": 8},
    {"name": "Narendra Modi", "profession": "Politician", "followers_millions": 200},
    {"name": "Barack Obama", "profession": "Politician", "followers_millions": 250},
    {"name": "Oprah Winfrey", "profession": "Host", "followers_millions": 90},
    {"name": "Justin Bieber", "profession": "Singer", "followers_millions": 310},
    {"name": "LeBron James", "profession": "Basketball Player", "followers_millions": 180},
    {"name": "Roger Federer", "profession": "Tennis Player", "followers_millions": 50},
    {"name": "Sachin Tendulkar", "profession": "Cricketer", "followers_millions": 45},
    {"name": "Khabane Lame", "profession": "Content Creator", "followers_millions": 160},
    {"name": "MrBeast", "profession": "YouTuber", "followers_millions": 300},
    {"name": "PewDiePie", "profession": "YouTuber", "followers_millions": 110},
    {"name": "Mark Zuckerberg", "profession": "Entrepreneur", "followers_millions": 12},
    {"name": "Rihanna", "profession": "Singer", "followers_millions": 250},
    {"name": "Drake", "profession": "Rapper", "followers_millions": 180},
    {"name": "Katy Perry", "profession": "Singer", "followers_millions": 150},
    {"name": "Tom Holland", "profession": "Actor", "followers_millions": 90},
    {"name": "Chris Hemsworth", "profession": "Actor", "followers_millions": 110},
    {"name": "Gal Gadot", "profession": "Actress", "followers_millions": 100},
    {"name": "Will Smith", "profession": "Actor", "followers_millions": 120},
    {"name": "Hrithik Roshan", "profession": "Actor", "followers_millions": 50},
    {"name": "Deepika Padukone", "profession": "Actress", "followers_millions": 85},
    {"name": "Alia Bhatt", "profession": "Actress", "followers_millions": 80},
    {"name": "Ranveer Singh", "profession": "Actor", "followers_millions": 75},
    {"name": "Gigi Hadid", "profession": "Model", "followers_millions": 80},
    {"name": "Zayn Malik", "profession": "Singer", "followers_millions": 65},
    {"name": "Post Malone", "profession": "Singer", "followers_millions": 70},
    {"name": "Kourtney Kardashian", "profession": "Influencer", "followers_millions": 220},
    {"name": "Khloé Kardashian", "profession": "Influencer", "followers_millions": 240},
    {"name": "Blake Lively", "profession": "Actress", "followers_millions": 40},
    {"name": "Ryan Reynolds", "profession": "Actor", "followers_millions": 50},
    {"name": "Camila Cabello", "profession": "Singer", "followers_millions": 65},
    {"name": "Shakira", "profession": "Singer", "followers_millions": 180}
]
